# Generated by Django 5.2.3 on 2026-06-18 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropFirm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('website', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='propfirms/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PropFirmChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=50)),
                ('account_size', models.DecimalField(decimal_places=2, max_digits=12)),
                ('challenge_type', models.CharField(default='Phase 1', max_length=50)),
                ('profit_target', models.DecimalField(decimal_places=2, max_digits=6)),
                ('daily_drawdown_limit', models.DecimalField(decimal_places=2, max_digits=6)),
                ('max_drawdown_limit', models.DecimalField(decimal_places=2, max_digits=6)),
                ('current_profit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('current_daily_drawdown', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('current_max_drawdown', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('peak_equity', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('passed', 'Passed'), ('failed', 'Failed'), ('verification', 'Verification Stage')], default='pending', max_length=20)),
                ('days_remaining', models.IntegerField(default=30)),
                ('total_days', models.IntegerField(default=30)),
                ('trading_platform', models.CharField(default='MT5', max_length=20)),
                ('ea_running', models.BooleanField(default=False)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='pfarm.propfirm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prop_challenges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TradeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument', models.CharField(max_length=50)),
                ('direction', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=10)),
                ('lot_size', models.DecimalField(decimal_places=2, max_digits=6)),
                ('entry_price', models.DecimalField(decimal_places=5, max_digits=12)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True)),
                ('stop_loss', models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True)),
                ('take_profit', models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True)),
                ('profit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_open', models.BooleanField(default=True)),
                ('open_time', models.DateTimeField()),
                ('close_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='pfarm.propfirmchallenge')),
            ],
            options={
                'ordering': ['-open_time'],
            },
        ),
        migrations.CreateModel(
            name='DailyEquity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('equity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('daily_pnl', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('drawdown', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('notes', models.TextField(blank=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_equity', to='pfarm.propfirmchallenge')),
            ],
            options={
                'verbose_name_plural': 'Daily Equities',
                'ordering': ['date'],
                'unique_together': {('challenge', 'date')},
            },
        ),
    ]
