# Generated by Django 5.2.3 on 2026-06-18 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterTrader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('bio', models.TextField(blank=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='traders/')),
                ('broker', models.CharField(blank=True, max_length=100)),
                ('trading_style', models.CharField(blank=True, max_length=100)),
                ('instruments', models.CharField(blank=True, max_length=300)),
                ('roi', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('win_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('max_drawdown', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('profit_factor', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('sharpe_ratio', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('total_trades', models.IntegerField(default=0)),
                ('followers', models.IntegerField(default=0)),
                ('monthly_roi', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('min_investment', models.DecimalField(decimal_places=2, default=100.0, max_digits=10)),
                ('fee_percentage', models.DecimalField(decimal_places=2, default=20.0, max_digits=4)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('risk_level', models.CharField(default='moderate', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='master_trader', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-roi'],
            },
        ),
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument', models.CharField(max_length=50)),
                ('direction', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=10)),
                ('entry_price', models.DecimalField(decimal_places=5, max_digits=12)),
                ('stop_loss', models.DecimalField(decimal_places=5, max_digits=12)),
                ('take_profit', models.DecimalField(decimal_places=5, max_digits=12)),
                ('lot_size', models.DecimalField(decimal_places=2, max_digits=6)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('pnl', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='copytrade.mastertrader')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CopySubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('total_pnl', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copy_subscriptions', to=settings.AUTH_USER_MODEL)),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='copytrade.mastertrader')),
            ],
            options={
                'unique_together': {('user', 'trader')},
            },
        ),
        migrations.CreateModel(
            name='PerformanceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('equity', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('daily_pnl', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('drawdown', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('trades_count', models.IntegerField(default=0)),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_history', to='copytrade.mastertrader')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('trader', 'date')},
            },
        ),
    ]
